function [desktopStruct, syntaxStruct] = getTheme(name)
%GETTHEME Returns theme definitions for a given name
% name: 'dracula', 'monokai', 'solarized', etc.

switch lower(name)
    case 'dracula'
        base = struct( ...
            'CodeColor', '#f8f8f2', ...
            'NormalColor', '#f8f8f2', ...
            'KeywordColor', '#ff79c6', ...
            'CommentColor', '#50fa7b', ...
            'StringColor', '#f1fa8c', ...
            'UnterminatedStringColor', '#ff5555', ...
            'SyntaxErrorColor', '#ff5555', ...
            'SystemCommandColor', '#bd93f9', ...
            'CodeAnalyzerWarningColor', '#ffb86c', ...
            'ValidationSectionColor', '#ffb86c', ...
            'ErrorColor', '#ff5555', ...
            'WarningColor', '#ffb86c', ...
            'HyperlinkColor', '#8be9fd', ...
            'VariableHighlightColor', '#6272a4', ...
            'VariablesWithSharedScopeColor', '#8be9fd', ...
            'CodeAnalyzerInfoColor', '#8be9fd', ...
            'AutofixHighlightColor', '#44475a');

        desktopStruct = struct( ...
            'dark', struct('ForegroundColor', '#f8f8f2', 'BackgroundColor', '#282a36'), ...
            'light', struct('ForegroundColor', '#f8f8f2', 'BackgroundColor', '#282a36'));

    case 'monokai'
        base = struct( ...
            'CodeColor', '#f8f8f2', ...
            'NormalColor', '#f8f8f2', ...
            'KeywordColor', '#f92672', ...
            'CommentColor', '#75715e', ...
            'StringColor', '#e6db74', ...
            'UnterminatedStringColor', '#e6db74', ...
            'SyntaxErrorColor', '#f92672', ...
            'SystemCommandColor', '#ae81ff', ...
            'CodeAnalyzerWarningColor', '#fd971f', ...
            'ValidationSectionColor', '#fd971f', ...
            'ErrorColor', '#f92672', ...
            'WarningColor', '#fd971f', ...
            'HyperlinkColor', '#66d9ef', ...
            'VariableHighlightColor', '#a6e22e', ...
            'VariablesWithSharedScopeColor', '#a6e22e', ...
            'CodeAnalyzerInfoColor', '#66d9ef', ...
            'AutofixHighlightColor', '#49483e');

        desktopStruct = struct( ...
            'dark', struct('ForegroundColor', '#f8f8f2', 'BackgroundColor', '#272822'), ...
            'light', struct('ForegroundColor', '#f8f8f2', 'BackgroundColor', '#272822'));

    case 'solarized'
        base = struct( ...
            'CodeColor', '#839496', ...
            'NormalColor', '#839496', ...
            'KeywordColor', '#859900', ...
            'CommentColor', '#586e75', ...
            'StringColor', '#2aa198', ...
            'UnterminatedStringColor', '#dc322f', ...
            'SyntaxErrorColor', '#dc322f', ...
            'SystemCommandColor', '#6c71c4', ...
            'CodeAnalyzerWarningColor', '#b58900', ...
            'ValidationSectionColor', '#b58900', ...
            'ErrorColor', '#dc322f', ...
            'WarningColor', '#b58900', ...
            'HyperlinkColor', '#268bd2', ...
            'VariableHighlightColor', '#93a1a1', ...
            'VariablesWithSharedScopeColor', '#268bd2', ...
            'CodeAnalyzerInfoColor', '#2aa198', ...
            'AutofixHighlightColor', '#073642');


        desktopStruct = struct( ...
            'dark', struct('ForegroundColor', '#839496', 'BackgroundColor', '#002b36'), ...
            'light', struct('ForegroundColor', '#839496', 'BackgroundColor', '#002b36'));

    case 'catppuccin'
        base = struct( ...
            'CodeColor', '#cdd6f4', ...
            'NormalColor', '#cdd6f4', ...
            'KeywordColor', '#f38ba8', ...
            'CommentColor', '#6c7086', ...
            'StringColor', '#a6e3a1', ...
            'UnterminatedStringColor', '#f38ba8', ...
            'SyntaxErrorColor', '#f38ba8', ...
            'SystemCommandColor', '#b4befe', ...
            'CodeAnalyzerWarningColor', '#f9e2af', ...
            'ValidationSectionColor', '#f9e2af', ...
            'ErrorColor', '#f38ba8', ...
            'WarningColor', '#f9e2af', ...
            'HyperlinkColor', '#89dceb', ...
            'VariableHighlightColor', '#cba6f7', ...
            'VariablesWithSharedScopeColor', '#89dceb', ...
            'CodeAnalyzerInfoColor', '#94e2d5', ...
            'AutofixHighlightColor', '#313244');

        desktopStruct = struct( ...
            'dark', struct('ForegroundColor', '#cdd6f4', 'BackgroundColor', '#1e1e2e'), ...
            'light', struct('ForegroundColor', '#cdd6f4', 'BackgroundColor', '#1e1e2e'));

    otherwise
        error('❌ Unknown theme: %s', name);
end

syntaxStruct = struct('dark', base, 'light', base);
end
